### ISSUE TITLE
[DEV][BACKEND] Create default post template for every new community

### ISSUE THREAD

**Issue by Ozmus** [SWE574-G3/SWE-574-G3#101]
**Description**
When creating community, the system shall create a default template including title, and comment as string.

**Comment by CankutER** [comment]
There is a bug in the code, cannot create more than one communities due to 'unique' constraint on the template name. Since each default template is being created with the same name, we receive an error.

**Comment by CankutER** [comment]
Bug fixed here https://github.com/SWE574-G3/SWE-574-G3/pull/106
