### ISSUE TITLE
[DOCS] Mockup: Recommendation Pages

### ISSUE THREAD

**Issue by Ozmus** [SWE574-G3/SWE-574-G3#12]
### Description:
Provide a description of documentation

- **Type of Documentation:**
  - [ ] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
Add Resource if applicable

**Comment by Oguzoz1** [comment]
[Recommendation Mockups](https://github.com/SWE574-G3/SWE-574-G3/wiki/Mock-Up-Screens#recommendation-system-mockup) is prepared and published.
