### ISSUE TITLE
[DEV][FRONTEND] Homepage Redesign

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#127]
**Description**
Currently homepage is displaying existing communities. This section will be shifted to "Communities List" and homepage will list latest posts from communities which user is following. 

**Suggestions of Solution**

- [x] Rename home to communities.
- [x] Form a homepage where combination of posts from joined communities.
- [x] If a user is not member of a community, select from interested ones.
- [x] If a user is not member of a community and there is no community with their interest select random posts.

**Comment by niloaydin** [comment]
This issue is resolved in this [PR](https://github.com/SWE574-G3/SWE-574-G3/pull/136).
