### ISSUE TITLE
[DEV][FRONTEND] Making header menu mobile friendly

### ISSUE THREAD

**Issue by ynsmrkrkmz** [SWE574-G3/SWE-574-G3#133]
**Description**
Please describe the feature

**Suggestions of Solution**
If applicable, add your own proposed solution

**Additional context**
Add any other context or screenshots about the feature request here. For example, screenshot of a similar feature on different application. Or even a drawing.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a description field to the Template model and updated the frontend and backend components to support creating templates with descriptions. This enhancement allows users to provide more context for each template.

You can review changes in this commit: https://github.com/mnmnk43434/SWE574-G3-SWE-574-G3-133/commit/536ede861f6a25d53c996638280849c697fae96a.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ynsmrkrkmz** [comment]
#135 Completed
