### ISSUE TITLE
[DESIGN] Create Use Case diagram for Recommendation system

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#15]
### Description:
Use Case diagram for community recommendation system should be created according to the requirements. The diagram will be then added to the wiki page of the related headline.

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
The system requirements for recommendation system can be found [here](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#recommendation-requirements).

**Comment by Ozmus** [comment]
Use Case Diagram for Recommendation system is added to [this wiki page.](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#use-case-diagram-for-recommendation-system ). Can you please review when you have time?
@niloaydin @ynsmrkrkmz @Oguzoz1 @CankutER
