### ISSUE TITLE
[DOCS] Creation of the ER diagram for the Database Design of the applciation

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#16]
### Description:
Provide a description of documentation

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
Add Resource if applicable

**Comment by ynsmrkrkmz** [comment]
Completed [ER Diagram](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#entity-relation-diagram)
