### ISSUE TITLE
[DESIGN] Class Diagram for Recommendation system of the application

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#17]
### Description:
Class diagram for community recommendation system should be created according to the requirements. The diagram will be then added to the wiki page of the related headline.

- **Type of Documentation:**
  - [x] Wiki page
  - [X] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
The system requirements for recommendation system can be found [here](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#recommendation-requirements).

**Comment by CankutER** [comment]
Duplicate, closing. Actual issue:
https://github.com/SWE574-G3/SWE-574-G3/issues/23
