### ISSUE TITLE
[DESIGN] Class Diagram for Activity Feed system of the application

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#19]
### Description:
Class diagram for activity feed system in the community should be created according to the requirements. The diagram will be then added to the wiki page of the related headline.

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [x] It exists need update
  - [ ] It doesn't exist
  
### Resources
The system requirements for recommendation system can be found [here](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#activity-feed-requirements).

**Comment by AhmetZ06** [comment]
[Class Diagram For Activity Feed](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#class-diagram-for-activity-feed) is added here.
