### ISSUE TITLE
[IMPORTANT] Branch Protection Rules

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#2]
**Description:**
We need to establish clear rules for merging code into key branches like main (or develop, etc.) to ensure code quality and maintain project stability. This issue is about setting up branch protection rules, defining merge policies, and ensuring appropriate review processes.

**Proposed Action:**
Deciding on:
- Protection Rules
- Pull Request Review
- Defining Merge Methods
- Preventing Force Push

**Resource:**
[Github Docs on Branch Protection Rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)

**Comment by Oguzoz1** [comment]
29.09.24 Meeting Results:
More advanced restriction rules will be established over time. However, temporary branch rules are set.

- Two ruleset has been established for two different branches.  (main - dev) branches.

**Comment by ynsmrkrkmz** [comment]
For `dev` branch following rules have been set:

1. Preventing branch deletion
2. Disallowing non-fast-forward updates
3. Requiring pull requests with at least two approving reviews
4. Dismissing stale reviews upon new pushes

For `main` branch following rules have been set:

1. Preventing branch deletion
2. Disallowing non-fast-forward updates
3. Requiring pull requests

Similar rules have been set for both branches. However, the team will be informed that feature pull requests should not be made directly to the `main` branch. Instead, all pull requests to the `main` branch must be created from the `dev` branch.
