### ISSUE TITLE
[DESIGN] Sequence Diagram for Activity Feed system of the application 

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#20]
### Description:
Sequence diagram for activity feed system in the community should be created according to the requirements. The diagram will be then added to the wiki page of the related headline.

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
[Add Resource if applicable](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#activity-feed-requirements)

**Comment by AhmetZ06** [comment]
[Sequence Diagrams For Activity Feed](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#class-diagram-for-activity-feed) is added here.
