### ISSUE TITLE
[DESIGN] Create ER diagram for the application

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#21]
### Description:
The system has already have ER diagram up until the requirements of creation of recommendation system and the activity feed. The ER diagram should be created for those functionality aligned with the current database system design. The diagram will be then added to the wiki page of the related headline.

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
Add Resource if applicable

**Comment by ynsmrkrkmz** [comment]
ER diagram has been updated. You can review my work by using this [link](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#entity-relation-diagram)
