### ISSUE TITLE
[DESIGN] Create Use Case diagram for Activity Feed system

### ISSUE THREAD

**Issue by niloaydin** [SWE574-G3/SWE-574-G3#22]
### Description:
Use Case diagram for activity feed system in the community should be created according to the requirements. The diagram will be then added to the wiki page of the related headline.

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
The system requirements for recommendation system can be found [here](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#activity-feed-requirements).

**Comment by niloaydin** [comment]
Use Case Diagram for Activity Feed is added to [this wiki page.](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#use-case-diagram-for-activity-feed-system). Can you please review when you have time?
@CankutER @ynsmrkrkmz @Ozmus @Oguzoz1 @AhmetZ06

**Comment by Oguzoz1** [comment]
@niloaydin We might need to add explanations to diagrams.

**Comment by niloaydin** [comment]
The use case diagram for activity feed system is added to the wiki. As the review made by Oguz, explanation is also added. The diagram can be reached through [this link.](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#use-case-diagram-for-activity-feed-system)
