### ISSUE TITLE
[DOCS] Update mockups to include screen for recommended communities

### ISSUE THREAD

**Issue by CankutER** [SWE574-G3/SWE-574-G3#24]
### Description:
Provide a description of documentation

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [x] It exists need update
  - [ ] It doesn't exist
  
### Resources
Add Resource if applicable

**Comment by Oguzoz1** [comment]
[Documentation](https://github.com/SWE574-G3/SWE-574-G3/wiki/Mock-Up-Screens#screen-3-recommended-communities-screen) is updated!
