### ISSUE TITLE
[DOCS] Contributing Documentation

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#3]
### Description:
File within the main-branch to keep all standardized documentation and coding practices including issues as well. The file should include the following:

- [x] #7
- [x] #10
- [x] #31
- [ ] Submitting Issue ( Choose issue template, fill required or applicable places, assign all collabs)

- **Type of Documentation:**
  - [x] Wiki page
  - [x] Design document
  - [x] Roadmap
  - [x] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

- **Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist
  
### Resources
[Example "How To Contribute" File](https://github.com/jessesquires/.github/blob/main/CONTRIBUTING.md)

**Comment by niloaydin** [comment]
is this tasks completed?
@ynsmrkrkmz @Ozmus @Oguzoz1 @CankutER @AhmetZ06

**Comment by niloaydin** [comment]
All of these documents can be found in [wiki](https://github.com/SWE574-G3/SWE-574-G3/wiki).
