### ISSUE TITLE
[DEV][BACKEND] Recommendation Engine

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#43]
**Description**
Implement a recommendation system that displays highlighted posts based on popularity and newness, allows users to filter posts, and tailors content based on user-selected communities and interests.

**Requirements*

- [ ] The system will display highlights, which are collections of posts based on popularity and newness (RR01).
- [ ] Highlights will consist of 70% popular posts and 30% new posts (RR02).
- [ ] After registration, users will be presented with a list of communities or interests to select from (RR03).
- [ ] The system will use the user’s selected communities and interests to recommend relevant content (RR04).
- [ ] Users can filter posts by most liked, most commented, or most recent (RR05).
- [ ] When creating a new community, users must select at least three predefined tags (RR06).

**Suggested Solutions**
Please refer to meeting notes about labelling. 

[Meeting 3](https://github.com/SWE574-G3/SWE-574-G3/wiki/Meeting-Notes#meeting-3)
[Meeting 2 Discussion Topic 2](https://github.com/SWE574-G3/SWE-574-G3/wiki/Meeting-Notes#discussion)

**Additional context**
[Requirements](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#recommendation-requirements)
[Design Docs](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#software-design-for-recommendation-engine-class-and-sequence-diagrams)
[Mock-ups](https://github.com/SWE574-G3/SWE-574-G3/wiki/Mock-Up-Screens)

**Comment by niloaydin** [comment]
This issue is outdated. Issues belong to recommendation engine is created seperately.
