### ISSUE TITLE
[DEV][BACKEND] Activity Stream implementation in a community

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#44]
#### **Description**
Implement a community-specific activity feed that logs and displays significant user actions within a community. The feed should be visible only to registered community members and allow filtering and browsing of past activities.

#### **Requirements**
- [x] The system will log all significant user actions within a community (AFR01).
- [x]  Each community will have a dedicated **activity feed** (AFR02).
- [x] Only **registered users** of a community can view its activity feed (AFR03, AFR04).
- [x] The feed will display in a **timeline view**, with the most recent actions at the top (AFR05).
- [x]  Users can **filter** the feed by action type (AFR06).
- [x] The system will store **historical activity logs** for users to browse past activities (AFR07).
- [x] Actions taken by **moderators or community owners** will be highlighted for visibility (AFR08).

**Additional context**
[Requirements](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#activity-feed-requirements)
[Design Documents](https://github.com/SWE574-G3/SWE-574-G3/wiki/Design-Representations#sequence-diagrams-of-logged-activities-for-activity-feed)
[Mockup Screen](https://github.com/SWE574-G3/SWE-574-G3/wiki/Mock-Up-Screens#activity-stream-mock-up)

**Comment by niloaydin** [comment]
This issue is resolved in [this PR](https://github.com/SWE574-G3/SWE-574-G3/pull/59)
