### ISSUE TITLE
[DEV][BACKEND] Invitation System

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#45]
#### **Description**
Implement an invitation system that allows users to send, accept, reject, list, and cancel invitations to private communities. This functionality should be available to community owners, moderators, and users, following specific permissions.

#### **Requirements**
1. **Users** can:
   - List invitations sent to them (UR07).
   - Accept invitations sent to them (UR08).
   - Reject invitations sent to them (UR09).

2. **Community Owners** can:
   - Send invitations to users for private communities (CR07).
   - List all invitations they have sent (CR08).
   - Cancel any sent invitations (CR09).

3. **Community Moderators** can:
   - Send invitations to users for private communities (CR10).
   - List all invitations they have sent (CR11).
   - Cancel any sent invitations (CR12).

4. **Private Community Recruitment**:
   - Recruitment to a private community must only happen via invitation (SIR10).
   - Any user in a private community can send an invitation to another user (SIR11).

**Additional context**
[User Requirements Invitation](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#user-requirements)
[Community Requirements Invitation](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#community-requirements)
[Private Community Recruitment](https://github.com/SWE574-G3/SWE-574-G3/wiki/Requirements#security-and-integration)
[Mockup](https://github.com/SWE574-G3/SWE-574-G3/wiki/Mock-Up-Screens#invitation-mock-up)

**Comment by ynsmrkrkmz** [comment]
#60 Sending invitation backend

**Comment by ynsmrkrkmz** [comment]
#67 #75 #76 Completed

**Comment by ynsmrkrkmz** [comment]
#56 #100 Completed
