### ISSUE TITLE
[DOCS] Deployment Procedure on Wiki

### ISSUE THREAD

**Issue by Oguzoz1** [SWE574-G3/SWE-574-G3#5]
### Description:
We need a clear and detailed deployment procedure documented in the Wiki to ensure that deployments are consistent, easy to follow, and error-free. This document will serve as a guide for anyone deploying the application in various environments.

### Suggested Deployment Documentation Content:
Wiki might include the following:
- Pre-Deployment (Code Review and Branch Check)
- Environment Setup (Configuration of Environment)
- Deployment Prerequisites and Instructions ( Docker, Aws etc)
- Any automation tool

**Type of Documentation:**
  - [x] Wiki page
  - [ ] Design document
  - [ ] Roadmap
  - [ ] Guidelines (e.g., coding standards, contribution guidelines)
  - [ ] Other: [Specify]

**Current State:** 
  - [ ] It exists need update
  - [x] It doesn't exist

**Comment by CankutER** [comment]
Deployment procedure is documented in the wiki page below.
https://github.com/SWE574-G3/SWE-574-G3/wiki/Coding-Standards#deployment-procedure
